FROM bitnami/spark:latest

# Install Python dependencies
USER root
RUN apt-get update && apt-get install -y python3-pip
COPY requirements.txt /app/requirements.txt
RUN pip3 install -r /app/requirements.txt

# Set working directory
WORKDIR /app

# Set Spark environment variables (optional)
ENV SPARK_HOME=/opt/bitnami/spark
ENV PATH=$SPARK_HOME/bin:$PATH

CMD ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
